In [1]:
import numpy as np

In [3]:
a= np.array([1,2,3,4, 0.4])
print(a)

[1.  2.  3.  4.  0.4]


In [4]:
a= np.array([[[[1,2,3],[3,4,6],[10,20,40],[2,3,4]]]])
a.ndim

4

In [6]:
num1 = int(input("Enter num 1 : "))
num2 = int(input("Enter num 2 : "))
num3 = int(input("Enter num 3 : "))

arr = np.array([[
    [num1, num2,num3],
    [num2, num2**2,num2**2+num3 ],
    [num3, num3+num2**2,num3+num2**2+num3 ]]])
arr

Enter num 1 :  1
Enter num 2 :  2
Enter num 3 :  3


array([[[ 1,  2,  3],
        [ 2,  4,  7],
        [ 3,  7, 10]]])

In [ ]:
print(arr)

print(arr[0,1,1])

[[[ 1  2  3]
  [ 2  4  7]
  [ 3  7 14]]]
4


In [4]:
a = np.array([1,2,3,4,5,6,7,8,9])

a[a%2==0]

array([2, 4, 6, 8])

In [7]:
b = a[a>3]
b

array([4, 5, 6, 7, 8, 9])